insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("노트북", "computer", 100, "LG전자", 10, "gram")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("운동화", "shoes", 200, "아디다스", 20, "슈퍼스타")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("러닝화", "shoes", 300, "나이키", 30, "초경량 러닝화")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("노트북", "computer", 400, "삼성전자", 40, "오디세이")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("노트북", "computer", 500, "애플", 50, "mac os")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("휴대폰", "phone", 600, "애플", 60, "iphone 11")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("휴대폰", "phone", 700, "LG전자", 70, "v20")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("휴대폰", "phone", 800, "삼성전자", 80, "galaxy s20")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("세탁기", "house", 900, "삼성전자", 90, "드럼형 세탁기")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("냉장고", "house", 1000, "LG전자", 100, "엘지디오스")